name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest bandit

      - name: Run flake8 (lint)
        run: |
          PYTHONPATH=. flake8 .

      - name: Run Bandit security scan
        run: |
          PYTHONPATH=. bandit -r detectors parsers api

      - name: Run tests
        run: |
          PYTHONPATH=. pytest -v --maxfail=1 --disable-warnings
